cityrover.graph-engine {

  postgres {
    host     = ${POSTGIS_HOST}
    port     = ${POSTGIS_PORT}
    database = ${POSTGIS_DB}
    user     = ${POSTGIS_USER}
    password = ${POSTGIS_PASSWORD}
  }

  inputPbf = "data/maps/gcc-states-260716.osm.pbf"

  # MUST match docker volume mount
  outputDir = "/opt/cityrover/graph-engine/output"
}
