cityrover.sim {

  # Number of rovers to simulate
  numRovers = 50

  # Simulation tick interval (ms)
  tickMillis = 1000

  # Total simulation duration (minutes)
  simulationDurationMinutes = 30

  graph {
    # Path to graph-engine output directory
    # Must contain:
    #   nodes.parquet
    #   edges.parquet
    #   spatial-index.bin
    #
    # Example: "/home/aleksei/Projects/.../graph-engine/output"
    path = "/home/aleksei/Projects/spatio_temporal_stream_processing/batch-processing/city-rover/graph-engine/output"
  }

  kafka {
    # Kafka broker inside Docker network
    bootstrapServers = "kafka-1:19092"

    # Raw telemetry topic
    topic = "rover-telemetry-raw"
  }
}
