cityrover.sim {

  numRovers = 50
  tickMillis = 1000
  simulationDurationMinutes = 30

  graph {
    # MUST match docker volume mount
    path = "/opt/cityrover/graph-engine/output"
  }

  kafka {
    bootstrapServers = ${KAFKA_BOOTSTRAP_SERVERS}
    topic = "rover-telemetry-raw"
  }
}
