cityrover {

  kafka {
    bootstrap = "kafka-1:19092"

    topics {
      raw-telemetry = "rover-telemetry-protobuf"
    }
  }

  pipeline {
    # For lowest latency, disable event-time watermarks entirely.
    # Processing-time windows do not need watermarks.
    watermark-delay-ms = 0

    # Window size for processing-time windows.
    # 200–500 ms is the sweet spot for sub-second latency.
    window-size-ms = 5000
  }

  latency {
    profiler {
      enabled = true

      # Sample every Nth event
      sample-rate = 1
    }
  }
}
