services:

  # ----------
  # CITY-ROVER
  # ----------
  graph-engine:
    build:
      context: ../batch-processing/city-rover/graph-engine
      dockerfile: Dockerfile
    container_name: cityrover-graph-engine
    volumes:
      - graph-data:/opt/cityrover/graph-engine/output
      - ../data/maps:/app/data/maps
    networks:
      - city-rover-net
    environment:
      POSTGIS_HOST: postgis-real-deal
      POSTGIS_PORT: 5432
      POSTGIS_DB: cre_db
      POSTGIS_USER: cre_user
      POSTGIS_PASSWORD: cre_password
      JAVA_OPTS: "-Xmx4g"
    restart: "no"

  rover-simulator:
    build:
      context: ../batch-processing/city-rover/rover-simulator
      dockerfile: Dockerfile
    container_name: cityrover-rover-simulator
    depends_on:
      graph-engine:
        condition: service_completed_successfully
      kafka-1:
        condition: service_started
    volumes:
      - graph-data:/opt/cityrover/graph-engine/output
    networks:
      - city-rover-net
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:19092
      JAVA_OPTS: "-Xmx4g"


  # -----
  # INFRA
  # -----
  kafka-1:
    image: apache/kafka:3.8.0
    container_name: kafka-1
    ports:
      - "19092:19092"
      - "19093:19093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:19093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092,CONTROLLER://0.0.0.0:19093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      CLUSTER_ID: d8ce1515-401e-44d4-a444-1b6dba479047
    networks:
      - city-rover-net
    restart: always

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.6.0
    container_name: kafka-connect
    depends_on:
      - kafka-1
      - schema-registry
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka-1:19092"
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_PLUGIN_PATH: "/usr/share/java"
      CONNECT_LOG4J_LOGGERS: "org.reflections=ERROR"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8084"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8084"
    ports:
      - "8083:8083"
    volumes:
      - ./connect-plugins:/usr/share/java
    networks:
      - city-rover-net
    restart: unless-stopped

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: schema-registry
    depends_on:
      - kafka-1
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka-1:19092"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    ports:
      - "8084:8081"
    networks:
      - city-rover-net

  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_ENDPOINT_URL: http://minio:9002
    command: server /data --console-address ":9001" --address ":9002"
    volumes:
      - minio-data:/data
    ports:
      - "9002:9002"
      - "9001:9001"
    networks:
      - city-rover-net
    restart: unless-stopped

  minio-setup:
    image: minio/mc:latest
    container_name: minio-setup
    depends_on:
      minio:
        condition: service_started
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Waiting for MinIO..."
        until mc alias set local http://minio:9002 minioadmin minioadmin >/dev/null 2>&1; do
          echo "MinIO not ready yet..."
          sleep 2
        done
        echo "MinIO is ready."
        mc mb --ignore-existing local/cityrover-iceberg
        mc mb --ignore-existing local/spark-data
        mc mb --ignore-existing local/airflow-logs
        echo "All MinIO buckets initialized successfully."
    networks:
      - city-rover-net
    restart: "no"

  hive-postgres:
    image: postgres:15.2
    container_name: hive-postgres
    hostname: hive-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres-azure-data:/var/lib/postgresql/data
      - ../hive-metastore/01-create-hive-metastore.sql:/docker-entrypoint-initdb.d/01-create-hive-metastore.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - city-rover-net
    restart: always

  hive-metastore:
    build:
      context: ../hive-metastore
      dockerfile: Dockerfile
    image: alexflames77/custom-hive-metastore:latest
    container_name: hive-metastore
    hostname: hive-metastore
    environment:
      SERVICE_NAME: hivemetastore
      DB_TYPE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: hive-postgres
      DB_PORT: 5432
      DB_NAME: hive_metastore
      METASTORE_PORT: 9083
      METASTORE_THRIFT_PROTOCOL_VERSION: TCompactProtocol
      METASTORE_HANDLER_RETRY_ATTEMPTS: 5
      METASTORE_STARTUP_DELAY: 30
      HIVE_CONF_DIR: /opt/hive/conf
      HIVE_AUX_JARS_PATH: /opt/hive/lib
      HIVE_METASTORE_DB_TYPE: postgres
      HADOOP_HOME: /opt/hadoop
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
      HADOOP_CLASSPATH: /opt/hadoop/share/hadoop/common/lib/*:/opt/hadoop/share/hadoop/common/*:/opt/hadoop/share/hadoop/hdfs/*:/opt/hadoop/share/hadoop/hdfs/lib/*:/opt/hadoop/share/hadoop/mapreduce/*:/opt/hadoop/share/hadoop/yarn/*:/opt/hadoop/share/hadoop/yarn/lib/*
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9083"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      hive-postgres:
        condition: service_healthy
    ports:
      - "9096:9083"
    volumes:
      - ../hadoop-conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ../hive-conf/hive-site.xml:/opt/hive/conf/hive-site.xml:ro
    networks:
      - city-rover-net
    restart: unless-stopped

  trino:
    image: trinodb/trino:422
    container_name: trino
    hostname: trino
    ports:
      - "8090:8080"
    volumes:
      - ../trino/etc:/etc/trino:ro
      - ../trino/data:/var/trino
    depends_on:
      hive-metastore:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - city-rover-net
    restart: unless-stopped

  flink-jobmanager:
    image: flink:2.3.0-scala_2.12-java17
    container_name: flink-jobmanager
    hostname: flink-jobmanager
    command: jobmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
    ports:
      - "8081:8081"
      - "9090:9090"
    volumes:
      - ../flink-conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    networks:
      - city-rover-net
    restart: unless-stopped

  flink-taskmanager:
    image: flink:2.3.0-scala_2.12-java17
    container_name: flink-taskmanager
    hostname: flink-taskmanager
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
    ports:
      - "9091:9090"
    depends_on:
      flink-jobmanager:
        condition: service_started
    volumes:
      - ../flink-conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    networks:
      - city-rover-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9095:9090"
    networks:
      - city-rover-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - city-rover-net
    restart: unless-stopped

  # ----
  # JOBS
  # ----
  trajectory-lakehouse-writer-job:
    build:
      context: ../batch-processing/city-rover/spark-jobs/trajectory-lakehouse-writer-job
      dockerfile: Dockerfile
    container_name: cityrover-trajectory-lakehouse-writer-job
    depends_on:
      hive-metastore:
        condition: service_healthy
      kafka-1:
        condition: service_started
      minio:
        condition: service_started
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_EC2_METADATA_DISABLED: "true"
      CITYROVER_KAFKA_BOOTSTRAP: kafka-1:19092
      CITYROVER_ICEBERG_CATALOG: cityrover
      CITYROVER_ICEBERG_NAMESPACE: cityrover
      CITYROVER_ICEBERG_TABLE: telemetry_raw
      CITYROVER_ICEBERG_METASTORE_URI: thrift://hive-metastore:9083
      CITYROVER_ICEBERG_CHECKPOINT: s3://cityrover-iceberg/checkpoints/trajectory-lakehouse-writer
      CITYROVER_ICEBERG_S3_ENDPOINT: http://minio:9002
      CITYROVER_ICEBERG_S3_ACCESS_KEY: minioadmin
      CITYROVER_ICEBERG_S3_SECRET_KEY: minioadmin
      CITYROVER_ICEBERG_S3_PATH_STYLE_ACCESS: "true"
    networks:
      - city-rover-net
    restart: "no"

  trajectory-visualizer-job:
    build:
      context: ../batch-processing/city-rover/spark-jobs/trajectory-visualizer-job
      dockerfile: Dockerfile
    container_name: cityrover-trajectory-visualizer-job
    depends_on:
      kafka-1:
        condition: service_started
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:19092
      JAVA_OPTS: "-Xmx2g"
    volumes:
      - graph-data:/opt/cityrover/graph-engine/output
    networks:
      - city-rover-net
    restart: "no"

  rover-map-visualizer:
    build:
      context: ../batch-processing/city-rover/rover-map-visualizer
      dockerfile: Dockerfile
    container_name: cityrover-map-visualizer
    environment:
      VISUALIZER_OUTPUT_DIR: /opt/spark/work-dir/pipelines/trajectory-viewer/output
      VISUALIZER_WEBROOT: web
      JAVA_OPTS: "-Xmx512m"
    volumes:
      - trajectory-data:/opt/spark/work-dir/pipelines/trajectory-viewer/output
    ports:
      - "8080:8080"
    networks:
      - city-rover-net
    restart: always

  rover-flink-latency-job:
    build:
      context: ../stream-processing/city-rover/rover-flink-latency
      dockerfile: Dockerfile
    container_name: rover-flink-latency-job
    depends_on:
      flink-jobmanager:
        condition: service_started
      flink-taskmanager:
        condition: service_started
      kafka-1:
        condition: service_started
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:19092
      MINIO_ENDPOINT: http://minio:9002
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      FLINK_JOB_PARALLELISM: 1
    networks:
      - city-rover-net
    restart: "no"


volumes:
  minio-data:
    driver: local

  postgres-azure-data:
    driver: local

  grafana-data:
    driver: local

  graph-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aleksei/Projects/telecom_analytics_4.0/spark/pipelines/trajectory-viewer/output

  trajectory-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aleksei/Projects/telecom_analytics_4.0/spark/pipelines/trajectory-viewer/output

networks:
  city-rover-net:
    external: true
    name: city-rover-net



# ./start-system-city-rover.sh
# ./run-rover-simulator.sh
# ./run-trajectory-job.sh
# ./run-map-visualizer.sh
# ./run-lakehouse-job.sh
# ./run-latency-job.sh
# docker compose -f docker/docker-compose.city-rover.yml build --no-cache graph-engine
# docker compose -f docker/docker-compose.city-rover.yml build --no-cache rover-simulator
# docker compose -f docker/docker-compose.city-rover.yml build --no-cache trajectory-visualizer-job
# docker compose -f docker/docker-compose.city-rover.yml build --no-cache rover-map-visualizer
# docker compose -f docker/docker-compose.city-rover.yml build --no-cache trajectory-lakehouse-writer-job
# docker compose -f docker/docker-compose.city-rover.yml build --no-cache rover-flink-latency-job

# 1. Deploy kafka-connector:
# curl -X POST -H "Content-Type: application/json" \
#      --data @json-to-protobuf-smt.json \
#      http://localhost:8083/connectors
#
# 2. Check status:
# curl http://localhost:8083/connectors/json-to-protobuf-telemetry/status
#
# 3. Verify schema registry:
# curl http://localhost:8084/subjects
#
# 4. Verify Protobuf messages in Kafka:
# kafka-console-consumer \
#   --bootstrap-server localhost:19092 \
#   --topic raw-telemetry-proto \
#   --from-beginning

# wget https://repo1.maven.org/maven2/io/debezium/debezium-connector-kafka/2.5.0.Final/debezium-connector-kafka-2.5.0.Final-plugin.zip \
#      -O debezium-kafka.zip
# or https://repo1.maven.org/maven2/io/debezium/debezium-connector-kafka/2.5.0.Final/
#
# unzip debezium-kafka.zip -d connect-plugins/
