-- Find the number of events generated by every active rover
SELECT
    r.rover_id,
    COUNT(e.event_id) AS event_count
FROM rovers r
LEFT JOIN rover_events e
    ON r.rover_id = e.rover_id
WHERE r.status = 'active'
GROUP BY r.rover_id;
