blob:
  server:
    port: '6124'
taskmanager:
  memory:
    process:
      size: 1728m
  numberOfTaskSlots: 4
metrics:
  reporter:
    prom:
      port: 9090
      factory:
        class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
  reporters: prom
parallelism:
  default: 1
jobmanager:
  rpc:
    address: flink-jobmanager
  memory:
    process:
      size: 1600m
env:
  java:
    opts:
      all: -XX:+UseZGC -XX:+ZGenerational -XX:ZUncommitDelay=30 -XX:+AlwaysPreTouch
query:
  server:
    port: '6125'
