global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['flink-jobmanager:9090']

  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['flink-taskmanager:9090']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9002']
