cityrover {

  kafka {
    bootstrap = "kafka-1:19092"

    topics {
      enriched-telemetry = "rover-telemetry-enriched"
    }

    consumer-group = "cityrover-consumer"
  }

  cassandra {
    host = "cassandra"
    port = 9042
    keyspace = "cityrover"
    table = "telemetry_enriched"

    write {
      batch-size = 50
      max-retries = 3
    }
  }

  pipeline {
    # Writer job does not use event-time windows.
    watermark-delay-ms = 0
  }
}
